sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: fj+tcRIoN1uZkvaskikadqB32H25U/aZ43U6UwOcAERQKQmjy9leAOCj/RnboBBUAS2c6ZR/iioxWtOVW3VtMeW6Zu/A3JOBc6G5EObMWH2UzDtx97iuREM+U/EY9isqQ+iF7WyBkbkgQUFCxABwUGKKB9yH7PJWa6Mh931sPHf69U7euwMeI3PVzEHG/BCt1X85d1uBqP9ELYWD35u32qTMIgT8vJ34Lh5rLR5CF2ePkIjIVFUYkYbESBhoSMDOsONghY4QOS0T1caAebCVFnjGUx1fKznjbpUebCPmZZct7ZHk5d3nQuPAd8bCEk4if83Dbs0RZoswTdv/5L+BMr+k/Y9dyQb7FLY6yDyZgITnamqi9JgBZlPxsssvUZzJrclF5G/mFDs1FIYqt3BUc1CLb4wvU2EgjwLhJvK7wRxHHlip5LE9G38MAXQLylGOpjwGHX3jDv0IOB/DbvIyz1NRW3kmUPpRaskUCNa6oDBlKi/jnGH30led47Q7/xgBxmRTGSD/dBxzov/vuygrJaW3rJj5F2y7rSrVzuAIkfnMeP/J3hyRzOWku2nVp3LwP7rpMmUCe6VeX9Cy7qlAFpAcBeE7AChyINTwOj8HZfTmxaXj5sWrVbmtQ5DVvrkpZ2+4EWlRZwIUjLsx5+i+uxbhv1Z9J8sL/9G5lW2tJ1c=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Insectivorous-Plants_5765
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy